version: '16.2'
services:
  postgres_db:
    image: postgres:latest
    container_name: dgng-backend 
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres123
    ports:
    - '5433:5433'
    volumes:
    - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local